export const USER_REGISTER_START = "USER_REGISTER_START";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";
export const CLEAR_USER_STATE = "CLEAR_USER_STATE";
