export const CLEAR_ROOM_ERROR = "CLEAR_ROOM_ERROR";

export const ALL_ROOMS_START = "ALL_ROOMS_START";
export const ALL_ROOMS_SUCCESS = "ALL_ROOMS_SUCCESS";
export const ALL_ROOMS_FAIL = "ALL_ROOMS_FAIL";
