export const CLEAR_ROOMS_ERROR = "CLEAR_ROOM_ERROR";

export const ALL_ROOMS_START = "ALL_ROOMS_START";
export const ALL_ROOMS_SUCCESS = "ALL_ROOMS_SUCCESS";
export const ALL_ROOMS_FAIL = "ALL_ROOMS_FAIL";

export const CLEAR_ROOM_ERROR = "CLEAR_ROOM_ERROR";

export const GET_ROOM_DETAIL_START = "GET_ROOM_DETAIL_START";
export const GET_ROOM_DETAIL_SUCCESS = "GET_ROOM_DETAIL_SUCCESS";
export const GET_ROOM_DETAIL_FAIL = "GET_ROOM_DETAIL_FAIL";
